services:
  db:
    image: mysql:8.0
    container_name: dbdelivery_routing_lab
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: superSecret
      MYSQL_DATABASE: delivery_routing_lab
      MYSQL_USER: dbeaver
      MYSQL_PASSWORD: superSecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
